Reformatted code. Deleted unused unteractors
logotet/Weather_App pull request #18
Opened 2022-06-29 12:21 UTC by logotet

2022-06-29 13:31 UTC, sando22 requested changes

2022-06-29 13:31 UTC, sando22 commented on app/src/main/java/com/example/weatherapp/ui/current/ForecastFragment.kt
> +        val cityName = args.location
You don't need `cityName` as variable at all here. Just set it to the view model. The view model should hold instance of it and make checks when needed.

2022-06-29 13:31 UTC, sando22 commented on app/src/main/java/com/example/weatherapp/ui/current/ForecastFragment.kt
> +            viewModel.refreshData(cityName)
And here you won't need to pass it as parameter, because you will already has it in the view model.

2022-06-29 13:31 UTC, sando22 commented on app/src/main/java/com/example/weatherapp/ui/current/ForecastFragment.kt
> +                binding?.refresh?.isRefreshing = false
Do you handle the refresh state when error occurs?

2022-06-29 14:52 UTC, logotet commented on app/src/main/java/com/example/weatherapp/ui/current/ForecastFragment.kt
> +                binding?.refresh?.isRefreshing = false
I added the same call when the result was error

2022-06-29 14:52 UTC, logotet commented on app/src/main/java/com/example/weatherapp/ui/current/ForecastFragment.kt
> +        val cityName = args.location
I removed the variable.

2022-06-29 14:53 UTC, logotet commented on app/src/main/java/com/example/weatherapp/ui/current/ForecastFragment.kt
> +            viewModel.refreshData(cityName)
The name of the city is now provided from the view model.

2022-06-30 05:05 UTC, sando22 commented on app/src/main/java/com/example/weatherapp/repository/Repository.kt
> +import kotlinx.coroutines.runBlocking
Do you need this?

2022-06-30 05:05 UTC, sando22 commented on app/src/main/java/com/example/weatherapp/ui/current/ForecastFragment.kt
> +        viewModel.setupData(args.location, unitSystem)
Change location argument name to be more descriptive. `cityName` was a good option

2022-06-30 05:05 UTC, sando22 commented on app/src/main/java/com/example/weatherapp/ui/current/ForecastViewModel.kt
> +        getNetworkWeatherResponse(cityName)
Check if cityName is not null.

2022-06-30 07:36 UTC, sando22 approved these changes

2022-06-30 07:37 UTC, merged